app/Http/routes.php
<?php

use Illuminate\Support\Facades\Redis;


//Home
Route::get('/', ['as' => 'home', 'uses' => 'PagesController@index']);

//Calendar
Route::get('/booking/calendar', ['as'=>'booking.calendar', 'uses'=>'BookingController@calendar']);

Route::resource('/booking/events', 'BookingController');

Route::get('/booking/api', ['as'=>'booking.api', 'uses'=>'BookingController@api']);

Route::post('ajaxify/check_availability/{id}', 'BookingController@check_availability');

Route::group(['middleware' => 'auth:all'], function () {
    Route::resource("bookmarks", "BookmarksController");
    Route::resource("/user-location", "LocationsController");
    Route::resource("/events", "EventController");
    Route::resource('/reminders', 'ReminderController');
    Route::get('/fetch/jobs','JobsController@fetch_requests');
    Route::get('/user/reports/{id}', 'Admin\ReportsController@user_stats');
});

//push notifications devices
Route::resource('/devices', 'DevicesController');

//bookings
Route::post('/bookings/save', ['as' => 'bookings.save', 'uses' => 'BookingController@store']);
Route::group(['middleware' => 'auth:administrator'], function () {
    Route::resource('/bookings', 'BookingsController');
});


//feedback
Route::post('/feedback', 'AdminController@feedback');

//options
Route::get('/options', 'Admin\ClassificationController@category_options');

//search venues
Route::get('/venues/search','VendorController@venueSearch');

// Added by Gaurang Ghinaiya
Route::get('/shop', 'Front\ProductController@home');
Route::get('/shop/product/{product_slug}', 'Front\ProductController@show');
Route::resource('/shop/cart', 'Front\CartController');
Route::resource('/shop/checkout', 'Front\CheckoutController');
Route::get('/shop/finalstep/{id?}', 'Front\CheckoutController@finalStep');
Route::get('/shop/pespalipn/{id?}', 'Front\CheckoutController@pespalIpn');
Route::post('/shop/save-user-order-details', 'Front\CheckoutController@save_user_order_details');
Route::get('/shop/cod-order-confirmation/{id}', 'Front\CheckoutController@cod_order_confirmation');
Route::get('/shop/cart-count', 'Front\CartController@cartCount');
Route::get('/shop/category/{category_slug}', 'Front\ProductController@catProduct');
Route::get('/shop/subcategory/{subcategory_slug}', 'Front\ProductController@subCatProduct');

Route::group(['prefix' => '/shop/admin', 'as' => 'shop.admin.', 'middleware' => 'auth:administrator'], function () {
    Route::resource('/home', 'AdminShop\AdminShopController', [
        'names' => [
            'index' => 'myshop.index',
            'create' => 'myshop.create',
            'store' => 'myshop.store',
            'show' => 'myshop.show',
            'edit' => 'myshop.edit',
            'update' => 'myshop.update',
            'destroy' => 'myshop.destroy',
        ],
    ]);

    Route::resource('/category', 'AdminShop\CategoryController', [
        'names' => [
            'index' => 'category.index',
            'create' => 'category.create',
            'store' => 'category.store',
            'show' => 'category.show',
            'edit' => 'category.edit',
            'update' => 'category.update',
            'destroy' => 'category.destroy',
        ],
    ]);

    Route::resource('/subcategory', 'AdminShop\SubcategoryController', [
        'names' => [
            'index' => 'subcategory.index',
            'create' => 'subcategory.create',
            'store' => 'subcategory.store',
            'show' => 'subcategory.show',
            'edit' => 'subcategory.edit',
            'update' => 'subcategory.update',
            'destroy' => 'subcategory.destroy',
        ],
    ]);
//    Route::get('/get-sub-category/{id}', 'AdminShop\SubcategoryController@getSubCategory');

//    Route::resource('/users', 'AdminShop\UsersController');
//    Route::post('/user/paginate', 'AdminShop\UsersController@paginateUser');

    Route::resource('/products', 'AdminShop\ProductsController', [
        'names' => [
            'index' => 'products.index',
            'create' => 'products.create',
            'store' => 'products.store',
            'show' => 'products.show',
            'edit' => 'products.edit',
            'update' => 'products.update',
            'destroy' => 'products.destroy',
        ],
    ]);
    Route::resource('/orders', 'AdminShop\ShopOrdersController', [
        'names' => [
            'index' => 'orders.index',
            'show' => 'orders.show',
            'edit' => 'orders.edit',
            'update' => 'orders.update',
            'destroy' => 'orders.destroy',
        ],
    ]);

//    Route::post('/product/paginate', 'AdminShop\ProductsController@paginate');
});
Route::get('shop/admin/product/images/{id}', ['as' => 'products.images', 'uses' => 'AdminShop\ProductsController@images']);
Route::post('shop/admin/product/images/{id}', ['as' => 'products.upload', 'uses' => 'AdminShop\ProductsController@upload']);
Route::get('shop/admin/product/images/delete/{id}', ['as' => 'products.delete', 'uses' => 'AdminShop\ProductsController@deleteImage']);
// EOF of Gaurang Ghinaiya
Route::get('onboard/jobs', 'OnboardController@checkRedirect');
Route::get('jobs/intro', 'OnboardController@jobIntro');
//forum
Route::get('forum', '\Riari\Forum\Frontend\Http\ControllersCategoryController@index');
//landing-pages

Route::get('/welcome/{slug}', ['as' => 'landing-pages', 'uses' => 'PagesController@landing']);
Route::get('/packages/{slug}', ['as' => 'landing-pages', 'uses' => 'PagesController@landing']);

Route::group(['middleware' => 'job',], function () {
//jobs
    Route::get('jobs/status/{job_id}/{status}', 'JobsController@returnBidStatus');
    Route::get('jobs/events/', 'JobsController@viewEvents');
    Route::get('jobs/events/{id}', 'JobsController@viewEventJobs');
    Route::get('jobs/child-class', 'JobsController@childClass');
    Route::get('jobs/create', 'JobsController@create');
    Route::get('jobs/{id}', 'JobsController@show');
    Route::post('jobs/{id}', 'JobsController@show');
    Route::resource('jobs', 'JobsController');
    Route::resource('bids', 'BidsController');
    Route::get('vendr/jobs', 'JobsController@jobsBoard');
    Route::get('jobs/create/success/{token}', 'JobsController@jobSuccess');
    Route::get('jobs/get/user_number_blade', 'JobsController@user_number_blade');
    Route::get('jobs/get/job_posted', 'JobsController@jobPosted');
    Route::get('jobs/restore/{id}', 'JobsController@restore');

//bids
    Route::get('job/bid/{id}', ['as' => 'job.view', 'uses' => 'JobsController@viewJob']);
    Route::post('job/bid/{id}', ['as' => 'job.bid', 'uses' => 'JobsController@bidJob']);
    Route::post('bids/change-status', ['as' => 'bids.change_status', 'uses' => 'BidsController@change_bid_status']);
});

//budget tool
Route::resource('budget', 'BudgetController');
Route::post('bids/status/{id}', 'JobsController@status');

Route::group(['middleware' => 'auth:all'], function () {
    //dashboard
    Route::resource('dashboard', 'DashboardController');
    Route::get('/dashstats', ['as' => 'dashstats', 'uses' => 'DashboardController@getUserStats']);
});


//contact
Route::get('contact', ['as' => 'contact', 'uses' => 'PagesController@getContact']);
Route::get('contact-us', ['as' => 'contact-us', 'uses' => 'PagesController@getContactAgain']);
Route::post('contact', 'PagesController@sendContactInfo');
Route::get('advertise', ['as' => 'advertise', 'uses' => 'PagesController@getAdvertise']);
Route::get('reviews', ['as' => 'reviews', 'uses' => 'PagesController@getReviews']);

//Terms & conditions
Route::get('terms-and-conditions', ['as' => 'terms', 'uses' => 'PagesController@getTerms']);

//Policy
Route::get('privacy-policy', ['as' => 'policy', 'uses' => 'PagesController@getPolicy']);

//About
Route::get('about', ['as' => 'about', 'uses' => 'PagesController@getAbout']);
//Blog
Route::get('/blog', ['as' => 'blog', 'uses' => 'BlogController@index']);
Route::get('/blog/{slug}', 'BlogController@showPost');

//Honeymoon Subscribe
Route::post('/honeymoon-subscription/create', 'PagesController@saveSubscription');
Route::get('honeymoon-subscription', ['middleware' => 'auth:administrator', 'uses' => 'PagesController@viewSubscriptions']);

//Admin
Route::group(['namespace' => 'Admin', 'middleware' => 'auth:administrator'], function () {
    Route::resource('admin/boosts', 'BoostsController');
    Route::resource('admin/boostcategories', 'BoostsCategoryController');
    Route::get('admin/page', 'AdminController@getHome');
    Route::resource('admin/post', 'PostController', ['except' => 'show']);
    Route::resource('admin/category', 'CategoryController', ['except' => 'show']);
    Route::get('admin/upload', 'UploadController@index');
    Route::post('admin/upload/file', 'UploadController@uploadFile');
    Route::delete('admin/upload/file', 'UploadController@deleteFile');
    Route::post('admin/upload/folder', 'UploadController@createFolder');
    Route::delete('admin/upload/folder', 'UploadController@deleteFolder');
    Route::resource('classification', 'ClassificationController');

});
Route::group(['middleware' => 'auth:administrator'], function () {
    Route::get('/sms/get', 'Admin\ReportsController@getNotifications'); 
    Route::get('/sms/post', 'Admin\ReportsController@postNotifications'); 
    Route::get('admin/jobs/reports', 'Admin\ReportsController@jobs_reports');
    Route::get('admin/jobs-credits/reports', 'Admin\ReportsController@job_credits_reports');
    Route::get('admin/classifications/subcategory', ['as' => 'subcategory.create', 'uses' =>'Admin\ClassificationController@add_root_parent']);
    Route::post('admin/classifications/subcategory', ['as' => 'subcategory.store', 'uses' => 'Admin\ClassificationController@store_root_parent']);
    Route::get('admin/classifications/sub-subcategory', 'Admin\ClassificationController@add_parent');
    Route::post('admin/classifications/sub-subcategory', ['as' => 'sub-subcategory.store', 'uses' => 'Admin\ClassificationController@store_parent']);

app/Models/BoostCategory.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class BoostCategory extends Model
{
    use SoftDeletes;
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'boost_category';

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'parent_id'];

    public static $rules = [
        'name' => 'required|string',
    ];

    public static $db_attributes = [
        'name', 'parent_id',
    ];

    public function boosts()
    {
        return $this->belongsToMany('App\Models\Boost', 'boosts', 'category_id')->withTimestamps();
    }

    public function parent()
    {
        return $this->belongsTo('App\Models\BoostCategory', 'parent_id');
    }

    public function children()
    {
        return $this->hasMany('App\Models\BoostCategory', 'parent_id', 'id');
    }

    /**
     * @param $request
     * @param $id
     *
     * @return bool|null
     */
    public static function saveBoostCategory($request, $id)
    {
        $attributes = $request->all();
        if(empty($attributes)) {
            return false;
        }

        $attributes['id'] = (isset($attributes['id'])) ? $attributes['id'] : $id;

        $_attributes = array_merge((array)$attributes, [
            'name'      => $attributes['name'],
            'parent_id' => (isset($attributes['parent_id'])) ? $attributes['parent_id'] : null,
        ]);

        $_attributes = array_only($_attributes, static::$db_attributes);

        $boost_category = (isset($attributes['id']) && $attributes['id']) ? static::findOrFail($attributes['id']) : null;

        if($boost_category) {
            if(!isset($attributes['parent_id'])) {
                $attributes['parent_id'] = $boost_category->id;
            }
            $boost_category->update($_attributes);

            return $boost_category;
        }

        $boost_category = parent::updateOrCreate($_attributes, $_attributes);

        if($boost_category && !isset($attributes['parent_id'])) {
            $boost_category->parent_id = $boost_category->id;
            $boost_category->save();
        }

        return $boost_category;
    }
}

resources/views/admin/boostcategories/create.blade.php
<!-- Bootstrap -->
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">

<!-- DataTable Bootstrap -->
<link href="https://cdn.datatables.net/1.10.11/css/dataTables.bootstrap.min.css" rel="stylesheet">
<div class="container">
    <div class="container">

        <h1>Create Boost Category</h1>

        @if ($errors->any())
            <ul class="alert alert-danger">
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        @endif

        <hr/>
        {!! Form::open(['route' => 'admin.boostcategories.store', 'class' => 'form-horizontal', 'files' => true]) !!}

        @include('admin.boostcategories.fields')

        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-3">
                {!! Form::submit('Create', ['class' => 'btn btn-primary form-control']) !!}
            </div>
        </div>

        {!! Form::close() !!}
    </div>
</div>

resources/views/admin/boostcategories/edit.blade.php
<!-- Bootstrap -->
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">

<!-- DataTable Bootstrap -->
<link href="https://cdn.datatables.net/1.10.11/css/dataTables.bootstrap.min.css" rel="stylesheet">
<div class="container">
    <div class="container">

        <h1>Edit Boost Category {{ $boostcategory->id }}</h1>

        @if ($errors->any())
            <ul class="alert alert-danger">
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        @endif
        <hr/>
        {!! Form::model($boostcategory, [
        'route' => ['admin.boostcategories.update', $boostcategory->id],
        'method' => 'patch',
        'class' => 'form-horizontal',
            'files' => true]) !!}

        @include('admin.boostcategories.fields')


        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-3">
                {!! Form::submit('Update', ['class' => 'btn btn-primary form-control']) !!}
            </div>
        </div>
        {!! Form::close() !!}

    </div>
</div>

resources/views/admin/boostcategories/fields.blade.php
@if(isset($categories))
    <div class="form-group">
        {!! Form::label('parent_id', 'Parent Category: ', ['class' => 'col-sm-3 control-label']) !!}
        <div class="col-sm-6">
            <select name="parent_id" placeholder=category" class="form-control">
                <option value="">No Parent Category</option>
                <optgroup label="Category">
                    @foreach($categories as $category)
                        <option value="{{$category->id}}">{{$category->name}}</option>
                    @endforeach
                </optgroup>
            </select>
        </div>
    </div>
@endif

<div class="form-group {{ $errors->has('name') ? 'has-error' : ''}}">
    {!! Form::label('name', 'Name', ['class' => 'col-sm-3 control-label']) !!}
    <div class="col-sm-6">
        {!! Form::text('name', null, ['class' => 'form-control']) !!}
        {!! $errors->first('name', '<p class="help-block">:message</p>') !!}
    </div>
</div>

resources/views/admin/boostcategories/index.blade.php
<!-- Bootstrap -->
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">

<!-- DataTable Bootstrap -->
<link href="https://cdn.datatables.net/1.10.11/css/dataTables.bootstrap.min.css" rel="stylesheet">
<div class="container">

    <h1>Boosts Categories
        <a href="{{ route('admin.boostcategories.create') }}" class="btn btn-primary btn-xs" title="Add New Boost">
            <span class="glyphicon glyphicon-plus" aria-hidden="true">
            </span>
        </a>
    </h1>
    <div class="table">
        <table class="table table-bordered table-striped table-hover">
            <thead>
            <tr>
                <th> Name</th>
                <th> Parent</th>
                <th> Children</th>
                <th>&nbsp;</th>
            </tr>
            </thead>
            <tbody>
            @foreach($boostcategories as $item)
                <tr>
                    <td>{{ $item->name }}</td>
                    <td>{{ @$item->parent->name }}</td>
                    <td>{{ $item->children->count() }}</td>
                    <td>
                        <a href="{{ route('admin.boostcategories.show', [$item->id]) }}" class="btn btn-success btn-xs"
                           title="View Boost"><span class="glyphicon glyphicon-eye-open" aria-hidden="true"/></a>
                        <a href="{{ route('admin.boostcategories.show', [$item->id]) }}/edit" class="btn btn-primary btn-xs"
                           title="Edit Boost"><span class="glyphicon glyphicon-pencil" aria-hidden="true"/></a>
                        {!! Form::open([
                            'method'=>'DELETE',
                            'route' => ['admin.boosts.destroy', $item->id],
                            'style' => 'display:inline'
                        ]) !!}
                        {!! Form::button('<span class="glyphicon glyphicon-trash" aria-hidden="true" title="Delete Boost" />', array(
                                'type' => 'submit',
                                'class' => 'btn btn-danger btn-xs',
                                'title' => 'Delete Boost',
                                'onclick'=>'return confirm("Confirm delete?")'
                        )) !!}
                        {!! Form::close() !!}
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        <div class="pagination-wrapper"> {!! $boostcategories->render() !!} </div>
    </div>

</div>
<!-- JavaScripts -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

<!-- Datatables -->
<script src="https://cdn.datatables.net/1.10.11/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.11/js/dataTables.bootstrap.min.js"></script>

resources/views/admin/boostcategories/show.blade.php
<!-- Bootstrap -->
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">

<!-- DataTable Bootstrap -->
<link href="https://cdn.datatables.net/1.10.11/css/dataTables.bootstrap.min.css" rel="stylesheet">
<div class="container">
    <div class="container">

        <h1>Boost Category - {{ $boostcategory->name }}
            <a href="{{ route('admin.boostcategories.show', [$boostcategory->id]) }}/edit"
               class="btn btn-primary btn-xs"
               title="Edit Boost"><span class="glyphicon glyphicon-pencil" aria-hidden="true"/></a>
            {!! Form::open([
                'method'=>'DELETE',
                'route' => ['admin.boostcategories.destroy', $boostcategory->id],
                'style' => 'display:inline'
            ]) !!}
            {!! Form::button('<span class="glyphicon glyphicon-trash" aria-hidden="true"/>', array(
                    'type' => 'submit',
                    'class' => 'btn btn-danger btn-xs',
                    'title' => 'Delete Boost',
                    'onclick'=>'return confirm("Confirm delete?")'
            ))!!}
            {!! Form::close() !!}
        </h1>
        <div class="table-responsive">
            <table class="table table-bordered table-striped table-hover">
                <tbody>

                <tr>
                    <th> Name</th>
                    <td> {{ $boostcategory->name }} </td>
                </tr>
                <tr>
                    <th> Parent Category</th>
                    <td> {{ $boostcategory->parent->name }} </td>
                </tr>
                <tr>
                    <th> Children</th>
                    <td> {{ $boostcategory->children->count() }} </td>
                </tr>

                </tbody>
            </table>
        </div>

    </div>