app/Http/routes.php
Route::group(['prefix' => 'admin', 'middleware' => 'auth:administrator'], function () {
    $a = 'admin.';
    Route::get('/', ['as' => $a . 'home', 'uses' => 'AdminController@getHome']);
    Route::get('/vendor/report', 'AdminController@TopVendors');
    Route::get('/activities/report', ['as' => 'activities-report', 'uses' => 'AdminController@allActivities']);
    Route::get('/userlist', 'Admin\UsersController@getUsers');
    Route::get('/users/delete/{id}', 'Admin\UsersController@destroy');
    Route::get('/users/restore/{id}', 'Admin\UsersController@restore');
    Route::get('/links', ['as' => 'admin.links', 'uses' => 'AdminController@index']);
});

Route::group(['prefix' => 'vndor', 'middleware' => 'auth:vendor'], function () {
    $a = 'vendor.';
    Route::get('/', ['as' => $a . 'home', 'uses' => 'VendorController@getHome']);
});

Route::group(['prefix' => 'user', 'middleware' => 'auth:user'], function () {
    $a = 'user.';
    Route::get('/', ['as' => $a . 'home', 'uses' => 'UserController@getHome']);
});

Route::group(['middleware' => 'auth:all'], function () {
    $a = 'authenticated.';
    Route::get('/logout', ['as' => $a . 'logout', 'uses' => 'Auth\AuthController@getLogout']);
});

//Confirm email
Route::get('register/verify/{confirmationCode}', ['as' => 'confirmation_path', 'uses' => 'Auth\AuthController@confirm']);

//Email rating
Route::get('/email/{rating}/{token}', ['as' => 'email_rating', 'uses' => 'AdminController@rating']);

//Messaging
Route::group(['prefix' => 'messages'], function () {
    Route::get('/', ['as' => 'messages', 'uses' => 'MessagesController@index']);
    Route::get('create', ['as' => 'messages.create', 'uses' => 'MessagesController@create']);
    Route::get('{id}/read', ['as' => 'messages.read', 'uses' => 'MessagesController@read']);
    Route::get('unread', ['as' => 'messages.unread', 'uses' => 'MessagesController@unread']);
    Route::post('/', ['as' => 'messages.store', 'uses' => 'MessagesController@store']);
    Route::get('{id}', ['as' => 'messages.show', 'uses' => 'MessagesController@show']);
    Route::put('/send/{id}', ['as' => 'messages.update', 'uses' => 'MessagesController@update']);
});

//Gallery
Route::group(['prefix' => 'gallery', 'before' => 'auth'], function () {
    Route::get('/list', ['as' => 'gallery.list', 'uses' => 'GalleryController@viewGalleryList']);
});

//search
Route::get('/search', ['as' => 'search', 'uses' => 'TagsController@mainSearch']);
Route::get('/find/{class_id}/{mainSearch}', ['as' => 'categoryLocation', 'uses' => 'TagsController@fetchSubCategory']);
Route::get('/find', 'TagsController@fetchSearchCategory');
Route::get('/search/{mainSearch}/{category}', 'TagsController@refineSearch');
Route::get('/vendorlistings', 'Admin\UsersController@vendorListings');

Route::group(['middleware' => 'auth:all',], function () {
    Route::resource('gallery/save', 'GalleryController@saveGallery');
    Route::get('gallery/delete/{id}', 'GalleryController@deleteGallery');
    Route::get('gallery/view-vid/{id}', 'GalleryController@viewGallerypics');
    Route::resource('video/do-upload', 'GalleryController@videoUploads');
    Route::resource('video/link-upload', 'GalleryController@LinkUploads');
    Route::get('gallery/edit/{id}', 'GalleryController@editGallery');
    Route::post('gallery/update/{id}', 'GalleryController@updateGallery');
    Route::post('gallery/output-tag', 'TagsController@outputTags');
});
//Admin Gallery Stuff
Route::group(['middleware' => 'auth:administrator',], function () {
    Route::resource('locations', 'Admin\LocationsController');
    Route::get('vendor/gallery/{id}', 'GalleryController@AdminViewGallery');
    Route::get('/vendor/credit-vendor/{id}', 'Admin\CreditController@create');
    Route::post('/vendor/credit-vendor/{id}', ['as' => 'vendor.credit-vendor', 'uses' => 'Admin\CreditController@store']);
});
//Gallery routes for both admin and vendor
Route::post('image/do-upload', 'GalleryController@doImageUpload');
Route::get('gallery/view/{id}', 'GalleryController@viewGallerypics');
Route::get('gallery/videos', 'TagsController@getVideos');
Route::get('image/delete/{id}', 'TagsController@deleteImage');


Route::resource('gallery/inspiration', 'TagsController@viewInspirationPage');
Route::resource('gallery/search', 'TagsController@searchInspirationPage');
Route::post('/idea/add', 'GalleryController@addIdea');


//vendors
Route::get('/{slug}', ['as' => 'vendor.view', 'uses' => 'VendorController@viewClassification']);
Route::get('/vendor/{slug}', ['as' => 'vendor.show', 'uses' => 'VendorController@showVendorAgain']);
Route::get('/vendors/{slug}', ['as' => 'vendor.show', 'uses' => 'VendorController@showVendor']);
Route::post('/vendor/{slug}/', ['as' => 'vendor.review', 'middleware' => 'auth:all', 'uses' => 'VendorController@saveReview']);
Route::post('/send-advert', ['middleware' => 'auth:all', 'uses' => 'VendorController@sendAdvert']);
Route::get('/contact/getvendors/{id}', 'VendorController@multipleVendors');
Route::get('/socials/{type}/{number}/{cookie_name}', 'VendorController@socialProof');


//profile
Route::group(['before' => 'auth'], function () {
    Route::get('profile/{id}', ['as' => 'profile', 'before' => 'auth', 'uses' => 'ProfileController@getVendorProfile']);
    Route::get('profile/edit/{id}', ['as' => 'edit.profile', 'before' => 'auth', 'uses' => 'ProfileController@editVendorProfile']);
    Route::post('profile/edit/{id}', ['as' => 'update.profile', 'before' => 'auth', 'uses' => 'ProfileController@updateVendorProfile']);
});

Route::post('/review-request', ['as' => 'review-request', 'before' => 'auth', 'uses' => 'VendorController@reviewRequest']);
Route::get('/reset/first/{id}', ['as' => 'firstPass', 'uses' => 'Auth\PasswordResetController@postFirstPass']);

//Activity Tracker
Route::get('/admin/log', ['as' => 'users.log', 'middleware' => 'auth:administrator', 'uses' => 'ActivitiesController@show']);
Route::post('/admin/messages', ['as' => 'admin.messages', 'middleware' => 'auth:administrator', 'uses' => 'MessagesController@messages']);
Route::get('/admin/messages', ['as' => 'admin.messages', 'middleware' => 'auth:administrator', 'uses' => 'MessagesController@messages']);
Route::get('/admin/users/{id}', ['middleware' => 'auth:administrator', 'uses' => 'Admin\UsersController@show']);
Route::post('/admin/leads', ['as' => 'admin.leads', 'middleware' => 'auth:administrator', 'uses' => 'MessagesController@threads']);
Route::get('/admin/leads', ['as' => 'admin.leads', 'middleware' => 'auth:administrator', 'uses' => 'MessagesController@threads']);

Route::group(['middleware' => 'auth:administrator'], function () {
    Route::resource('admin/bundles', 'Admin\CreditBundlesController');
});
Route::get('/shop/credits', ['as' => 'vendor-credits', 'middleware' => 'auth:vendor', 'uses' => 'Admin\CreditBundlesController@vendor_credits']);

Route::group(['prefix' => 'admin', 'middleware' => 'auth:administrator'], function () {
    Route::get('/reports/credits/', 'Admin\ReportsController@vendor_balance');
    Route::get('/reports/credits/user/{id}', 'Admin\ReportsController@vendor_balance');
    Route::get('/reports/credits/purchased', 'Admin\ReportsController@purchased_credits');
    Route::get('/reports/credits/under_hundred', ['as' => 'credits.under_hundred', 'uses' => 'Admin\ReportsController@under_hundred']);
    Route::get('/reports/rankings/', 'Admin\ReportsController@ranked_vendors');
    Route::get('/reports/free_credit_expiry/', 'Admin\ReportsController@free_credit_expiry');
    Route::resource('cron_tasks', 'CronTaskController', [
        'names' => [
            'create' => 'cron_tasks.create',
            'store' => 'cron_tasks.store',
            'index' => 'cron_tasks.index',
            'show' => 'cron_tasks.show',
            'edit' => 'cron_tasks.edit',
            'update' => 'cron_tasks.update',
            'destroy' => 'cron_tasks.destroy',
        ],
    ]);
    Route::resource('cron_schedules', 'CronScheduleController', [
        'names' => [
            'create' => 'cron_schedules.create',
            'store' => 'cron_schedules.store',
            'index' => 'cron_schedules.index',
            'show' => 'cron_schedules.show',
            'edit' => 'cron_schedules.edit',
            'update' => 'cron_schedules.update',
            'destroy' => 'cron_schedules.destroy',
        ],
    ]);

});
Route::get('api/category-dropdown', 'AdminShop\CategoryController@categoryDropDownData');
Route::get('api/classification-dropdown', 'Admin\ClassificationController@categoryDropDownData');

//Todo
Route::group(['prefix' => 'user', 'middleware' => 'auth:all'], function () {
    Route::resource('/todo', 'TodoController');
    Route::get('todo/view/{id}', ['as' => 'todo.view', 'uses' => 'TodoController@view']);
    Route::post('todo/status/{id}', ['as' => 'todo.status', 'uses' => 'TodoController@status']);
    Route::post('todo/note/{id}', ['as' => 'todo.note', 'uses' => 'TodoController@add_note']);
    Route::post('todo/add-subtask/', ['as' => 'todo.subtask', 'uses' => 'TodoController@subtask']);
});

//FileEntry
Route::group(['middleware' => 'auth:all'], function () {
    Route::post('fileentry/saveS3', ['as' => 'saveS3', 'uses' => 'FileEntryController@saveS3']);
});
Route::get('fileentry', 'FileEntryController@index');
Route::get('fileentry/get/{filename}', ['as' => 'getentry', 'uses' => 'FileEntryController@get']);
Route::post('fileentry/add', ['as' => 'addentry', 'uses' => 'FileEntryController@add']);
Route::get('fileentry/download/{filename}', ['as' => 'downloadentry', 'uses' => 'FileEntryController@download']);

/*
|--------------------------------------------------------------------------
| API routes
|--------------------------------------------------------------------------
*/
Route::get('/api', function () {
    return view('api.welcome');
});

Route::group(['prefix' => 'api', 'namespace' => 'API', 'middleware' => 'auth:administrator'], function () {
    Route::group(['prefix' => 'v1'], function () {

app/Http/Controllers/Admin/CreditBundlesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\CreditBundle;
use Illuminate\Http\Request;
use Carbon\Carbon;
use Session;


class CreditBundlesController extends Controller
{
    protected $is_ajax = false;

    public function __construct(Request $request)
    {
        $this->is_ajax = $request->ajax();
    }

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $creditbundles = CreditBundle::orderBy('id', 'desc')
                                     ->paginate(15);

        return $this->view('admin.creditbundles.index', compact('creditbundles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return $this->view('admin.creditbundles.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */
    public function store(Request $request)
    {
        return $this->save_credit_bundle($request);
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $creditbundles = CreditBundle::orderBy('id', 'desc')->paginate(15);

        return $this->view('admin.creditbundles.vendor-credits', compact('creditbundles'));
    }

    public function vendor_credits()
    {
        $creditbundles = CreditBundle::orderBy('id', 'desc')->paginate(15);

        return $this->view('admin.creditbundles.vendor-credits', compact('creditbundles'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $creditbundle = CreditBundle::findOrFail($id);

        return $this->view('admin.creditbundles.edit', compact('creditbundle'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function update($id, Request $request)
    {
        return $this->save_credit_bundle($request, $id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        CreditBundle::destroy($id);

        Session::flash('flash_message', 'CreditBundles successfully deleted!');

        return redirect('admin/bundles');
    }


    /**
     * @param Request $request
     * @param null    $id
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    private function save_credit_bundle(Request $request, $id = null)
    {
        $this->validate($request, CreditBundle::$input_validation);

        $credit = CreditBundle::saveCreditBundle($request, $id);

        if ($credit) {
            Session::flash('flash_message', 'CreditBundles successfully added!');

            return redirect('admin/bundles');
        }

        Session::flash('flash_message', 'Had trouble saving the bundle');

        return Redirect::back()
                       ->withErrors($credit);
    }

    /**
     * @param       $view
     * @param array $data
     *
     * @return $this|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    private function view($view, $data = [ ])
    {
        if ($this->is_ajax) {
            return view($view, $data);
        }

        return view('layouts.non-ajax-layout', $data)
            ->with('content', $view);

    }
}

resources/views/admin/creditbundles/create-edit-form-items.blade.php
<div class="form-group {{ $errors->has('name') ? 'has-error' : ''}}">
    {!! Form::label('name', 'Credit Bundle Name: ', ['class' => 'col-sm-3 control-label']) !!}
    <div class="col-sm-6">
        {!! Form::text('name', null, ['class' => 'form-control', 'required' => 'required']) !!}
        {!! $errors->first('name', '<p class="help-block">:message</p>') !!}
    </div>
</div>
<div class="form-group {{ $errors->has('description') ? 'has-error' : ''}}">
    {!! Form::label('description', 'Description: ', ['class' => 'col-sm-3 control-label']) !!}
    <div class="col-sm-6">
        {!! Form::textarea('description', null, ['class' => 'form-control', 'required' => 'required','rows'=>'5']) !!}
        {!! $errors->first('description', '<p class="help-block">:message</p>') !!}
    </div>
</div>
<div class="form-group {{ $errors->has('credits') ? 'has-error' : ''}}">
    {!! Form::label('credits', 'Credits: ', ['class' => 'col-sm-3 control-label']) !!}
    <div class="col-sm-6">
        {!! Form::text('credits', null, ['class' => 'form-control', 'required' => 'required']) !!}
        {!! $errors->first('credits', '<p class="help-block">:message</p>') !!}
    </div>
</div>
<div class="form-group {{ $errors->has('unit_price') ? 'has-error' : ''}}">
    {!! Form::label('unit_price', 'Unit Price: ', ['class' => 'col-sm-3 control-label']) !!}
    <div class="col-sm-6">
        {!! Form::text('unit_price', null, ['class' => 'form-control', 'required' => 'required']) !!}
        {!! $errors->first('unit_price', '<p class="help-block">:message</p>') !!}
    </div>
</div>
<div class="form-group {{ $errors->has('cost') ? 'has-error' : ''}}">
    {!! Form::label('cost', 'Bundle Cost: ', ['class' => 'col-sm-3 control-label']) !!}
    <div class="col-sm-6">
        {!! Form::text('cost', null, ['class' => 'form-control', 'required' => 'required']) !!}
        {!! $errors->first('cost', '<p class="help-block">:message</p>') !!}
    </div>
</div>
<div class="form-group {{ $errors->has('expiration_time') ? 'has-error' : ''}}">
    {!! Form::label('expiration_time', 'Expiration Time: ', ['class' => 'col-sm-3 control-label']) !!}
    <div class="col-sm-6">
        {!! Form::text('expiration_time', null, ['class' => 'form-control', 'required' => 'required']) !!}
        {!! $errors->first('expiration_time', '<p class="help-block">:message</p>') !!}
    </div>
</div>
<div class="form-group {{ $errors->has('cover_image_path') ? 'has-error' : ''}}">
    {!! Form::label('cover_image_path', 'Cover Image Path: ', ['class' => 'col-sm-3 control-label']) !!}
    <div class="col-sm-6">
        <input type="file" name="cover_image_path" class="form-control">
        {!! $errors->first('cover_image_path', '<p class="help-block">:message</p>') !!}
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-3 col-sm-3">
        {!! Form::submit('Save', ['class' => 'btn btn-primary form-control submit-btn']) !!}
    </div>
</div>
<script type="text/javascript">

     _container = $('main');
        add_overlay = function () {
            _container.css("position", "relative");
            var overlay = $('<div id="overlay"></div>').css({
                    position: "absolute",
                    width: "100%",
                    height: "100%",
                    top: 0,
                    left: 0,
                    "background-color": "rgba(255,255,255,0.1)" /*dim the background*/
                }),
                modal = $('<div id="this-modal"><div class="spinner"><div class="bounce1"></div><div class="bounce2"></div><div class="bounce3"></div></div>Loading...</div>').css({
                    position: "fixed",
                    width: "200px",
                    height: "200px",
                    top: "50%",
                    left: "50%",
                    "color": "#e9048b",
                    "margin-left": "-150px",
                    "margin-top": "-100px",
                    "text-align": "center",
                    "z-index": "10",
                });

            modal.appendTo(overlay.appendTo(_container));

        }
        remove_overlay = function () {
            $('#overlay').hide().remove();

        }

    $('.submit-btn').click(function (event) {
            event.preventDefault();
            console.log('hit');
            add_overlay();
            var form = $(this).closest('form')[0];
            var formData = new FormData(form);
            $.ajax({    
                        type:'POST',
                        url: $(this).closest('form').attr('action'),
                        data: formData,
                        // THIS MUST BE DONE FOR FILE UPLOADING
                        contentType: false,
                        processData: false,
                        // ... Other options like success and etc
                        success : function(data) {
                         remove_overlay();
                         $('.container').html(data);
                          
                        },
                        error:  function(data){
                            remove_overlay();
                            alert('error');
                        }
                    }); 
    });

</script>

resources/views/admin/creditbundles/create.blade.php
<div class="container">
     <h1>Create New Creditbundle</h1>
    <hr/>

    {!! Form::open(['route' => 'admin.bundles.store', 'class' => 'form-horizontal','files' => true, 'method' => 'post',]) !!}

    @include('admin.creditbundles.create-edit-form-items')
    {!! Form::close() !!}

    @if ($errors->any())
        <ul class="alert alert-danger">
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    @endif
</div>

resources/views/admin/creditbundles/credit-vendor.blade.php
<div class="container">
    <h1>Credit Vendor</h1>
    <hr/>

    {!! Form::open(['route' => 'vendor.credit-vendor', 'class' => 'form-horizontal','files' => true, 'method' => 'post',]) !!}

    <div class="form-group {{ $errors->has('credit') ? 'has-error' : ''}}">
        {!! Form::label('name', 'Name: ', ['class' => 'col-sm-3 control-label']) !!}
        <div class="col-sm-6">
            {!! Form::text('name', $user->first_name, ['class' => 'form-control', 'required' => 'required','disabled' => 'disabled']) !!}
            {!! $errors->first('name', '<p class="help-block">:message</p>') !!}
        </div>
    </div>
    <div class="form-group {{ $errors->has('credit') ? 'has-error' : ''}}">
        {!! Form::label('type', 'Type: ', ['class' => 'col-sm-3 control-label']) !!}
        <div class="col-sm-6">
            {!! Form::text('object_name', 'credits', ['class' => 'form-control', 'required' => 'required','disabled' => 'disabled']) !!}
            {!! $errors->first('object_name', '<p class="help-block">:message</p>') !!}
        </div>
    </div>
    <div class="form-group {{ $errors->has('credit') ? 'has-error' : ''}}">
        {!! Form::label('credit', 'Credits: ', ['class' => 'col-sm-3 control-label']) !!}
        <div class="col-sm-6">
            {!! Form::text('credit', null, ['class' => 'form-control', 'required' => 'required']) !!}
            {!! $errors->first('credit', '<p class="help-block">:message</p>') !!}
        </div>
    </div>
    {!! Form::hidden('user_id', $user->id) !!}
    <button type="submit" class="btn btn-primary"><span class="fi-dollar"></span> Credit User</button>
    {!! Form::close() !!}

    @if ($errors->any())
        <ul class="alert alert-danger">
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    @endif
</div>

resources/views/admin/creditbundles/edit.blade.php
<div class="container">
<h1>Edit Creditbundle</h1>
<hr/>

{!! Form::model($creditbundle, [
    'method' => 'PATCH',
    'route' => ['admin.bundles.update', $creditbundle->id],
    'class' => 'form-horizontal',
    'enctype'=>'multipart/form-data',
    'files' => true,
]) !!}

@include('admin.creditbundles.create-edit-form-items')
{!! Form::close() !!}

@if ($errors->any())
    <ul class="alert alert-danger">
        @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
        @endforeach
    </ul>
@endif

</div>

resources/views/admin/creditbundles/index.blade.php
<h1>Credit Bundles <a href="{{ route('admin.bundles.create') }}" class="button tiny warning right">Add New
        Creditbundles</a></h1>
<div class="table">

    <table class="table table-bordered table-striped table-hover">
        <thead>
        <tr>
            <th>S.No</th>
            <th>Name</th>
            <th>Description</th>
            <th>Credits</th>
            <th>Unit Price</th>
            <th>Cost</th>
            <th>Expiration Time</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        {{-- */$x=0;/* --}}
        @foreach($creditbundles as $item)
            {{-- */$x++;/* --}}

            <tr>
                <td>{{ $x }}</td>
                <td><a href="{{ url('admin/bundles', $item->id) }}">{{ @$item->name }}</a></td>
                <td>{{ @$item->description }}</td>
                <td>{{ $item->credits }}</td>
                <td>{{ $item->unit_price }}</td>
                <td>{{ @$item->cost }}</td>
                <td>{{ $item->expiration_time }}</td>
                <td>
                    <a href="{{ route('admin.bundles.edit', $item->id) }}">
                        <i class="fa fa-pencil-square-o"></i>
                    </a>
                    {!! Form::open([
                        'method'=>'DELETE',
                        'route' => ['admin.bundles.destroy', $item->id],
                        'style' => 'display:inline'
                    ]) !!}
                    {!! Form::submit('Delete', ['class' => 'btn btn-danger btn-xs']) !!}
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    <div class="pagination"> {!! $creditbundles->render() !!} </div>
</div>

resources/views/admin/creditbundles/non-ajax-layout.blade.php
@extends('layouts.main')

@section('content')
    @include(@$content)
@endsection

resources/views/admin/creditbundles/show.blade.php
<h1>Creditbundle</h1>
<div class="table-responsive">
    <table class="table table-bordered table-striped table-hover">
        <thead>
        <tr>
            <th>ID.</th>
            <th>Name</th>
            <th>Description</th>
            <th>Credits</th>
            <th>Cost</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>{{ $creditbundle->id }}</td>
            <td> {{ $creditbundle->name }} </td>
            <td> {{ $creditbundle->description }} </td>
            <td> {{ $creditbundle->credits }} </td>
            <td> {{ $creditbundle->cost }} </td>
        </tr>
        </tbody>
    </table>
</div>

resources/views/admin/creditbundles/vendor-credits.blade.php
<!-- START OF CREDITS HEADER -->
<section class="credits-header">
  <div class="row">
    <div class="small-12 columns">
      <span class="credits-icon"></span>
      <h2>About Blissful Credits</h2>
      <h6>Use credits to send quotes and get hired on Blissful</h6>
      <p>Blissful is a pay-per-quote system where you buy credits to send quotes to customers that are a good fit for your business. You only pay to quote, that’s it: we do not charge commission on jobs you complete or future jobs with the same customer and their referrals.</p>
    </div>
  </div>
</section>
<!-- END OF CREDITS HEADER -->
<!-- START OF CREDITS SELECT -->
<section class="credits-list">
  <div class="row">
    <div class="small-12 columns">
      <ul class="credits">
        <li>
            <div class="text-wrap">
              <h3>STARTER<br>PACK</h3>
              <hr>
              <h5>450 Credits</h5>
              <span>6-8 Jobs</span>
              <hr>
              <h6>Kshs 799.00</h6>
              <span>Kshs 1.78 per credit</span>
              <a class="button" onclick="window.location='/shop/product/460-credits';">BUY NOW</a>
            </div>
            <span class="backgrounds wrap">
              <span class="lcard"></span>
              <span class="rcard"></span>
              <span class="mcard"></span>
            </span>
        </li>
        <li>
            <div class="text-wrap">
              <h3>MOST<br>POPULAR</h3>
              <hr>
              <h5>900 Credits</h5>
              <span>11-15 Jobs</span>
              <hr>
              <h6>Kshs 1499.00</h6>
              <span>Kshs 1.67 per credit</span>
              <a class="button" onclick="window.location='/shop/product/900-credits';">BUY NOW</a>
            </div>
            <span class="backgrounds wrap">
              <span class="lcard"></span>
              <span class="rcard"></span>
              <span class="mcard"></span>
            </span>
        </li>
        <li>
            <div class="text-wrap">
              <h3>BEST<br>PRICE</h3>
              <hr>
              <h5>1500 Credits</h5>
              <span>18-25 Jobs</span>
              <hr>
              <h6>Kshs 2,400.00</h6>
              <span>Kshs 1.60 per credit</span>
              <a class="button" onclick="window.location='/shop/product/1500-credits';">BUY NOW</a>
            </div>
            <span class="backgrounds wrap">
              <span class="lcard"></span>
              <span class="rcard"></span>
              <span class="mcard"></span>
            </span>
        </li>
      </ul>
    </div>
  </div>
</section>
<!-- END OF CREDITS SELECT -->
<!-- START OF CREDITS FAQS -->
<section class="faqs">
  <div class="row">
    <div class="small-12 columns">
      <h3>FAQs</h3>
      <div class="credit-columns">
        <ul>
          <li>
            <h5>Do I have to use my credits on every request?</h5>
            <p>You must use credits to send a quote. However, you always have the option to read and pass on a customer request if it is not right for you.</p>
          </li>
          <li>
            <h5>How many credits do I need to apply for one job?</h5>
            <p>Each job is weighted and assigned a number of credits needed before a quote is sent. The number of credits needed is displayed along side each job.</p>
          </li>
          <li>
            <h5>Do I get charged for every message I send?</h5>
            <p>No we only deduct credits once, when you respond to a Job. The other messages that result from this one job are not billed.</p>
          </li>
          <li>
            <h5>What happens when I run out of credits?</h5>
            <p>You can buy more credits before you write your quote. You will alerted as soon as your credit balance drops below 100.</p>
          </li>
          <li>
            <h5>Can my Blissful credits expire?</h5>
            <p>The Blissful Credits that you buy do not expire. You can use them whenever you want, on the job you're interested in. However, the free credits given you new business on Blissful expire in 45 days.</p>
          </li>
        </ul>
      </div>
    </div>
  </div>
</section>
<!-- END OF CREDITS FAQS -->